env:
  browser: true
  es2021: true
extends:
  - standard-with-typescript
  - plugin:react/recommended
  - plugin:playwright/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
  tsconfigRootDir: __dirname
plugins:
  - react
rules: {}
settings:
  react:
    version: detect
