apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "auth.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "auth.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: jwt-keys
          secret:
            secretName: {{ .Release.Name }}-jwt-keys
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "run"
            - "--port={{ .Values.service.port }}"
            - "--host=0.0.0.0"
            - "--jwt-priv=/keys/private.json"
            - "--jwt-pub=/keys/public.json"
            - "--db=$(POSTGRES_URL)"
          volumeMounts:
            - name: jwt-keys
              mountPath: "/keys"
              readOnly: true
          env:
            - name: GIN_MODE
              value: "release"
            - name: POSTGRES_URL
              value: "postgresql://{{ .Values.postgresql.user }}:{{ .Values.postgresql.password }}@{{ .Values.postgresql.serviceName }}:5432/{{ .Values.postgresql.database }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
