{{- if .Values.gateway.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}
spec:
  parentRefs:
  - name: o11y-gateway
    kind: Gateway
    sectionName: https
  hostnames:
  {{- range .Values.gateway.hosts }}
    - {{ .host | quote }}
  {{- end }}
  rules:
  {{- range .Values.gateway.hosts }}
  - matches:
    {{- range .paths }}
    - path:
        type: {{ .pathType }}
        value: {{ .path }}
    {{- end }}
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /
    backendRefs:
    - name: {{ $.Release.Name }}
      kind: Service
      port: {{ $.Values.service.port }}
  {{- end }}
{{- end }}
