apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-jwt-keys
  labels:
    {{- include "auth.labels" . | nindent 4 }}
type: Opaque
data:
  private.json: |
   {{ .Values.secrets.jwt.privateKey }}
  public.json: |
    {{ .Values.secrets.jwt.publicKey }}
