kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
data:
  env.js: |
    window.env = {
        API_URL: "{{ .Values.apiURL }}"
        FARO_URL: "{{ .Values.faroURL }}"
        VERSION: {{ .Chart.AppVersion }}
    }


