issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - gocyclo
    - lll
    - depguard
    - gci
    - dogsled
    - gofumpt
    - tagalign