replicaCount: 1

apiURL: https://wall-api.local
faroURL: https://grafana-agent.local

image:
  repository: ghcr.io/chazapp/o11y/wall_front
  tag: 1.1.1
  pullPolicy: IfNotPresent

service:
  name: wall-front
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: wall.local  # Change to your desired host
  tls:
    secretName: wall-tls-secret
    hosts:
      - wall.local
