apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.serviceName }}
spec:
  selector:
    app: {{ .Values.postgresql.name }}
  ports:
  - name: postgresql
    protocol: TCP
    port: 5432
    targetPort: 5432
