apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: {{ .Values.service.port }}
  - name: metrics
    protocol: TCP
    port: 8081
    targetPort: 8081
  type: {{ .Values.service.type }}

