replicaCount: 1

config:
  allowedOrigins: https://wall.local
  otlpEndpoint: grafana-agent.monitoring:4317

image:
  repository: ghcr.io/chazapp/o11y/wall_api
  tag: 1.2.4
  pullPolicy: IfNotPresent

service:
  name: wall-api
  type: ClusterIP
  port: 8080

postgresql:
  name: postgresql
  serviceName: postgresql
  user: myuser
  password: mypassword
  database: wall_db
  storageClassName: standard
  storageSize: 1Gi

ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-opentelemetry: "true"
  enabled: true
  host: wall-api.local  # Change to your desired host
  tls:
    secretName: my-api-tls-secret
    hosts:
      - wall-api.local

beyla:
  enabled: false