replicaCount: 1

config:
  allowedOrigins: https://wall.local
  otlpEndpoint: grafana-agent.monitoring:4317

image:
  repository: ghcr.io/chazapp/o11y/wall_api
  tag: 2.1.0
  pullPolicy: IfNotPresent

service:
  name: wall-api
  type: ClusterIP
  port: 8080

serviceMonitor:
  enabled: true

postgresql:
  name: postgresql
  serviceName: postgresql
  user: myuser
  password: mypassword
  database: wall_db
  storageClassName: standard
  storageSize: 1Gi

ingress:
  enabled: true
  host: wall-api.local  # Change to your desired host
  tls:
    secretName: my-api-tls-secret
    hosts:
      - wall-api.local

