serviceMonitor:
  enabled: true

ingress:
  enabled: true
  hosts:
    - grafana.local
  tls: []

persistence:
  enabled: true

admin:
  existingSecret: grafana-admin
  userKey: username
  passwordKey: password

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://kube-prometheus-stack-prometheus:9090
        isDefault: true
      - name: Loki
        uid: loki
        type: loki
        url: http://loki-gateway
      - name: Tempo
        type: tempo
        url: http://tempo:3100
        jsonData:
          tracesToLogsV2:
            datasourceUid: "loki"
      - name: Pyroscope
        type: phlare
        url: http://pyroscope:4040/
      
extraObjects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: grafana-admin
    stringData:
      username: admin
      password: password