prometheus:
  ingress:
    enabled: false # Ingress are managed by the Gateway chart
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    enableRemoteWriteReceiver: true
    retention: 7d

grafana:
  enabled: false