loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: s3
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    s3:
      endpoint: http://minio:9000
      s3ForcePathStyle: true
      accessKeyId: loki
      secretAccessKey: lokiloki
      insecure: true
backend:
  replicas: 1
read:
  replicas: 1
write:
  replicas: 1

gateway:
  verboseLogging: false
  ingress:
    enabled: true
    hosts:
      - host: loki.local
        paths:
          - path: /
            pathType: Prefix
    tls: []

test:
  enabled: false
    
monitoring:
  serviceMonitor:
    enabled: true
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
  lokiCanary:
    enabled: false

