pyroscope:
  extraArgs:
    log.level: debug
  structuredConfig:
    storage:
      backend: s3
      s3:
        endpoint: "minio:9000"
        bucket_name: pyroscope
        access_key_id: pyroscope
        secret_access_key: pyroscopepyroscope
        insecure: true
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    annotations: {}
    # selector:
    #   matchLabels:
    #     app.kubernetes.io/name: phlare
    # subPath: ""
    # existingClaim:
agent:
  enabled: false