apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: global-http-redirect
spec:
  parentRefs:
  - name: o11y-gateway
    sectionName: root-http
  - name: o11y-gateway
    sectionName: api-http
  hostnames:
  - "o11y.local"
  - "api.o11y.local"
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
