apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing
  labels:
    app: landing
    {{- include "landing.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: landing
      {{- include "landing.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: landing
        {{- include "landing.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
