apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-landing
  labels:
    {{- include "landing.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: landing
    {{- include "landing.selectorLabels" . | nindent 4 }}
