name: Run Tests
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test-auth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
          check-latest: true

      - name: Install dependencies
        run: |
          cd apps/auth
          go mod download
          go mod verify

      - name: Run tests
        run: |
          cd apps/auth
          go test -v ./... -coverprofile=coverage.txt -covermode=atomic

