name: Apps E2E tests
on:
  push:
    paths:
      - apps/**

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: stable
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build API
        run: go build -o wall_api
        working-directory: apps/wall_api/
      - name: Build front-end
        run: yarn install && npm run build
        working-directory: apps/wall_front/
