name: Apps E2E tests
on:
  merge_group:
  push:
    paths:
      - apps/**
      - .github/workflows/e2e_tests.yaml

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: wallapi
          POSTGRES_USER: user
          POSTGRES_PASSWORD: foobar
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
         - 5432:5432
    steps:
      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build API
        run: go build -o wall_api
        working-directory: apps/wall_api/
      - name: Run API in background
        run: ./wall_api run --dbHost 127.0.0.1 --dbUser user --dbPassword foobar --dbName wallapi --allowedOrigins http://127.0.0.1:3000,http://localhost:3000 &
        working-directory: apps/wall_api/
    
      - name: Build front-end
        run: yarn install
        working-directory: apps/wall_front/
      - name: Run front-end in background
        run: yarn start &
        working-directory: apps/wall_front/
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: apps/wall_front/
      - name: Run Playwright tests
        run: npx playwright test
        working-directory: apps/wall_front/
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: apps/wall_front/playwright-report/
          retention-days: 30