name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 6" # Every saturday at 00:00
jobs:
    renovate:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Get token
              id: get_token
              uses: tibdex/github-app-token@v1
              with:
                private_key: ${{ secrets.RENOVATE_PRIVATE_KEY }}
                app_id: ${{ secrets.RENOVATE_APP_ID }}
            - name: Renovate
              uses: renovatebot/github-action@v39.2.1
              with:
                token: ${{ steps.get_token.outputs.token }}
                configurationFile: renovate.json