name: Wall Front tests
on:
  merge_group:
  push:
    # Path filtering not supported by CodeCov Flags
    # See #137
    # paths:
    #   - apps/wall_front/**
    #   - .github/workflows/wall_front_tests.yaml

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build front-end
        run: yarn install
        working-directory: apps/wall_front/

      - name: Tests front-end
        working-directory: apps/wall_front/
        run: yarn test

      - name: Upload app coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          flags: wall-front
          token: ${{ secrets.CODECOV_TOKEN }}
