name: Wall API tests
on:
  merge_group:
  push:
  # Path filtering not supported by CodeCov Flags
  # push:
  #   paths:
  #     - apps/wall_api/**
  #     - .github/workflows/wall_api_tests.yaml
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache-dependency-path:
            apps/wall_api/go.sum
      - name: Build
        run: go build -o wall_api
        working-directory: apps/wall_api/
      - name: Test
        run: go test ./... -cover -coverprofile=wall-api.cov
        working-directory: apps/wall_api
      - name: Upload app coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./apps/wall_api/wall-api.cov
          flags: wall-api
          token: ${{ secrets.CODECOV_TOKEN }}
