name: WallAPI
on:
  merge_group:
  push:
    paths:
      - apps/wall_api/**
      - .github/workflows/wall_api_tests.yaml
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache-dependency-path:
            apps/wall_api/go.sum
      - name: Build
        run: go build -o wall_api
        working-directory: apps/wall_api/
      - name: Test
        run: go test ./... -cover
        working-directory: apps/wall_api